CREATE TABLE IF NOT EXISTS app_user(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS app_user_role(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role varchar(255) NOT NULL);
CREATE TABLE IF NOT EXISTS app_user_user_role(app_user_id bigint NOT NULL, app_user_role_id bigint NOT NULL, PRIMARY KEY(app_user_id, app_user_role_id), FOREIGN KEY(app_user_id) REFERENCES app_user(id), FOREIGN KEY(app_user_role_id) REFERENCES app_user_role(id));

